### Envoyer une notification
POST http://localhost:8085/api/notifications/send
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0NTg3NjI3MywiZXhwIjoxNzQ1ODc5ODczfQ.yyh7BGVGoozCuZ0a78CGJV18syxjE1wu1iUQrnJ6g9o

{
  "to": "andersonmetsanoum@gmail.com",
  "subject": "Welcome",
  "content": "Welcome to AMCLOUD platform!"
}
